channels:
  - conda-forge
  - bioconda

dependencies:
  # Package to allow Jupyter Notebook or JupyterLab applications in one conda env to access other kernels (e.g. qiime2)
  - nb_conda_kernels==2.5.1

  # Packages from bioconda for IB134L
  - augustus==3.1
  - bcftools==1.23.1
  - blast==2.17.0
  - bwa==0.7.19
  - emboss==6.6.0
  - fastqc==0.12.1
  - hisat2==2.2.2
  - mafft==7.526
  - paml==4.10.10
  - plink==1.90b7.7
  - phyml==3.3.20220408
  - raxml-ng==2.0.1
  - samtools==1.23.1
  - seqtk==1.5
  - sra-tools==3.4.1
  - structure==2.3.4
  - subread==2.1.1
  - trimmomatic==0.40


  # Packages from bioconda for BioE-131, Fall 2020, Issue #1885
  - bowtie2==2.5.5
  - spades==4.2.0

  # Packages for MCB280A, Spring 2022
  - bedtools==2.31.1

  # Packages from bioconda for BIO1B
  - dendropy==5.0.8
  - muscle==5.3
  - raxml==8.2.13

  # bug w/notebook and traitlets: https://github.com/jupyter/notebook/issues/7048
  - traitlets==5.14.3

  # for MCELLBI201B (FA24) https://github.com/berkeley-dsep-infra/datahub/issues/5988
  - macs2==2.2.9.1

  # For https://github.com/berkeley-dsep-infra/datahub/issues/1846
  # Conda does not have these
  - pip:
    # MCB280A, Spring 2022
      - geonomics==1.4.1
      - nlmpy==1.2.0
      - pybedtools==0.12.0
    # Packages for MCB-160L iss #3942
      # DH-418 requires pandas 1.5.3, conflicts with otter-grader which needs 2.2.2
      # For https://github.com/berkeley-dsep-infra/datahub/issues/7575
      - allensdk==2.16.2
